currency = 100
days = 100

industries = [
  "Logging",
  "Mining",
  "Farming",
  "None",
]

global_actions = [
  { Pass = {} },
]

[resources."Wood"]
name = "Wood"
amount = 100
industries = ["None", "Logging"]
actions = [
  { Buy = { buy_price = 2 } },
  { Sell = { sell_price = 2 } },
]


[resources."Stone"]
name = "Stone"
amount = 100
industries = ["None", "Mining"]
actions = [
  { Buy = { buy_price = 1 } },
  { Sell = { sell_price = 1 } },
]

[resources."Gems"]
name = "Gems"
amount = 0
industries = ["None", "Mining"]
actions = [
  { Buy = { buy_price = 64 } },
  { Sell = { sell_price = 64 } },
]


[buildings."Mine"]
name = "Mine"
amount = 1
industries = ["None", "Mining"]
production = [["Stone", 1], ["Gems", 0.1]]
actions = [
  { Construct = { build_cost = [["Wood", 10], ["Stone", 20]] } },
]

[buildings."Sawmill"]
name = "Sawmill"
amount = 1
industries = ["None", "Logging"]
production = [["Wood", 1]]
actions = [
  { Construct = { build_cost = [["Wood", 20], ["Stone", 10]] } },
]