starting_day = 100
current_day = 100

industries = [
  "None",
  "Logging",
  "Mining",
]

global_actions = [
  { PassDay = {} },
]

[items."Wood"]
name = "Wood"
amount = 100
type = "Resource"
industries = ["None", "Logging"]
manual_actions = [
  { Buy = { buy_price = 2 } },
  { Sell = { sell_price = 2 } },
]
daily_actions = []


[items."Stone"]
name = "Stone"
amount = 100
type = "Resource"
industries = ["None", "Mining"]
manual_actions = [
  { Buy = { buy_price = 1 } },
  { Sell = { sell_price = 1 } },
]
daily_actions = []

[items."Gems"]
name = "Gems"
amount = 0
type = "Resource"
industries = ["None", "Mining"]
manual_actions = [
  { Buy = { buy_price = 4 } },
  { Sell = { sell_price = 4 } },
]
daily_actions = []

[items."Mine"]
name = "Mine"
amount = 1
type = "Building"
industries = ["None", "Mining"]
manual_actions = [
  { Construct = { build_cost = [["Wood", 20], ["Stone", 10]] } },
  { Deconstruct = { item_gain = [["Wood", 10], ["Stone", 5]] } },
]
daily_actions = [
  { Produce = { item_production =  [["Stone", 2], ["Gems", 1]] } },
]

[items."Sawmill"]
name = "Sawmill"
amount = 1
type = "Building"
industries = ["None", "Logging"]
manual_actions = [
  { Construct = { build_cost = [["Wood", 10], ["Stone", 20]] } },
  { Deconstruct = { item_gain = [["Wood", 5], ["Stone", 10]] } },
]
daily_actions = [
    { Produce = { item_production = [["Wood", 3]] } },
]